include_defs('//bucklets/maven_jar.bucklet')

VER = '2.13-SNAPSHOT'
REPO = MAVEN_LOCAL

maven_jar(
  name = 'acceptance-framework',
  id = 'com.google.gerrit:gerrit-acceptance-framework:' + VER,
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = '8ce1f6e65078bbcf03a1758f96b3ebca19b7fe3c',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)
